### ISSUE TITLE
Support for multi-module libraries!

### ISSUE THREAD

**Issue by aadrian** [xvik/generator-lib-java#4]
Please add support for multi-module projects (libraries).

As libs grow, they need to be split into several modules.

Thank you.

**Comment by xvik** [comment]
I was also planned it: :)
For now, you can look this multi-module project https://github.com/xvik/dropwizard-guicey-ext
(multi-module template will be based on it)

And it will not be added too soon. Most likely, next release will simply include updated plugins.

**Comment by xvik** [comment]
Simple multi-module project generation added in the latest [release](https://github.com/xvik/generator-lib-java/releases/tag/2.7.0)
