### ISSUE TITLE
Error installing generator-lib-java

### ISSUE THREAD

**Issue by thedewpoint** [xvik/generator-lib-java#5]
sudo npm install -g generator-lib-java
Password:
npm ERR! Darwin 17.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-lib-java"
npm ERR! node v9.2.1
npm ERR! npm  v3.10.5

npm ERR! Cannot convert undefined or null to object

**Comment by xvik** [comment]
Is it working now? 
I'm just using it with node 8 and did not check yet with node 9 (it's quite likely that node 9 breaks something - not the first time). I will check myself, just want to be sure if you already found a problem.

**Comment by thedewpoint** [comment]
@xvik 
It was an issue with my npm cache, once i cleared it and reinstalled it started working. I realized it wasn't related to your module when I went to install a different module but received the same error.
